/**
 * Programme templates restored on empty bootstrap and by ensureDefaultTemplates() when missing.
 * Match key: (name, tab) — existing rows are never overwritten.
 */
const DEFAULT_PROGRAMME_TEMPLATES = [
  {
    name: 'GW Standard',
    tab: 'groundworks',
    tower: 'T2',
    zone_name: 'Pour X',
    sequence: [
      'Blinding',
      'Drainage',
      'Insulation',
      'Waterproofing',
      'Pour',
      'Verts',
      'Podium Pour',
      'Crop Piles',
      'Form Pile Cap',
      'GF - Reinforcement - Shuttering',
    ],
    durations: [1, 2, 2, 1, 1, 4, 1, 1, 1, 2],
  },
  {
    name: 'INT Floor',
    tab: 'internals',
    tower: 'T1',
    zone_name: 'Floor X',
    sequence: [
      'All stitching works',
      'Corridor Ceiling Stitch',
      'Modular Ceiling Stitch',
      'Modular Floor Stitch',
      'Form Door Aperture',
      'Corridor Floor Stitch',
      'Stair Core Stitching',
      'MEP Riser',
      'MEP Corridor',
      'Ceiling Install',
      'Install Ceiling Panels',
      'Modular Linear Stitch',
      'Install Fire Doors',
      'Paint',
      'Commission',
    ],
    durations: [2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 3, 2],
  },
  {
    name: "T1 A's - Modular",
    tab: 'internals',
    tower: 'T1',
    zone_name: "A's",
    sequence: [
      'Temp lights',
      'All stitching works',
      'Form Traditional Risers',
      'MEP - Electrical',
      'MEP - Plumbing',
      'Sprinkler Install',
      'Ceiling Install',
      'Skirting',
      'Paint',
      'Install Ceiling Panels',
      'Decorative Linear Stitch',
    ],
    durations: [1, 3, 1, 1, 1, 1, 1, 1, 3, 1, 1],
  },
  {
    name: "T1 B's - Modular",
    tab: 'internals',
    tower: 'T1',
    zone_name: "A's",
    sequence: [
      'Temp lights',
      'All stitching works',
      'MEP - Electrical',
      'MEP - Plumbing',
      'Sprinkler Install',
      'Ceiling Install',
      'Skirting',
      'Paint',
      'Install Ceiling Panels',
      'Decorative Linear Stitch',
    ],
    durations: [1, 3, 1, 1, 1, 1, 1, 3, 1, 1],
  },
  {
    name: "T1 C's - Modular",
    tab: 'internals',
    tower: 'T1',
    zone_name: "A's",
    sequence: [
      'Temp lights',
      'All stitching works',
      'Form Door Aperture',
      'MEP - Electrical',
      'MEP - Plumbing',
      'Sprinkler Install',
      'Ceiling Install',
      'Skirting',
      'Paint',
      'Install Ceiling Panels',
      'Decorative Linear Stitch',
    ],
    durations: [1, 3, 1, 1, 1, 1, 1, 1, 3, 1, 1],
  },
  {
    name: 'T1 SC - Modular',
    tab: 'internals',
    tower: 'T1',
    zone_name: 'Stair Core L1 - L4',
    sequence: [
      'Stair Core Stitching',
      'Form Door Aperture',
      'Tape and Joint',
      'Handrail Installation',
      'Paint',
    ],
    durations: [2, 2, 3, 2, 3],
  },
  {
    name: 'T1 Lift and Riser',
    tab: 'internals',
    tower: 'T1',
    zone_name: 'L1 - L4',
    sequence: ['Lift Core Stitch', 'Riser Stitching', 'MEP Riser', 'Skirting', 'Paint'],
    durations: [2, 2, 3, 1, 3],
  },
];

module.exports = { DEFAULT_PROGRAMME_TEMPLATES };
